# Generated by Django 5.0.6 on 2024-07-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_room_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='createdAt',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='updatedAt',
            new_name='updated',
        ),
    ]
